ethtool: fix missing free of memory after failure
cppcheck warns:
test-common.c:106:2: error: Common realloc mistake: 'block' nulled but not freed upon failure [memleakOnRealloc]
 block = realloc(block, sizeof(*block) + size);
 ^

Fix the issue by storing a local copy of the old pointer and using that
to free the original if the realloc fails, as the manual for realloc()
suggests.

Signed-off-by: Jesse Brandeburg <jesse.brandeburg@intel.com>
Acked-by: Michal Kubecek <mkubecek@suse.cz>
---
v3: add ack by Michal
v2: original version